app/__init__.py
from flask import Flask, make_response, render_template, request
from .additional_functions import to_pretty_json
import werkzeug
from .config import Config


def create_app(test_config=None):
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_object(Config)
    from . import views
    app.register_blueprint(views.bp)
    app.jinja_env.filters['tojson_pretty'] = to_pretty_json

    @app.errorhandler(werkzeug.exceptions.NotFound)
    def not_found(e):
        return make_response(render_template('404.html', request_url=request.url), 404)

    @app.errorhandler(werkzeug.exceptions.BadRequest)
    def handle_bad_request(e):
        return make_response(render_template('400.html', request_url=request.url), 400)

    return app

app/views.py
import os
import app.additional_functions as ad_funcs
from flask import request, redirect, flash, Blueprint, current_app, render_template, session, abort, send_from_directory
from werkzeug.utils import secure_filename


bp = Blueprint('views', __name__, url_prefix='/api/v1.0')

@bp.route('/upload', methods=['GET', 'POST'])
def upload():
    if request.method == 'POST':
        file = request.files['file']
        if 'file' not in request.files:
            flash('No file part')
            return redirect(request.url)
        if file.filename == '':
            flash('No selected file')
            return redirect(request.url)
        elif file and ad_funcs.allowed_file(filename=file.filename):
            filename = secure_filename(file.filename)
            file.save(os.path.join(current_app.config['UPLOAD_FOLDER'], filename))
            data_set = ad_funcs.read_csv(os.path.join(current_app.config['UPLOAD_FOLDER'], filename))
            session['data_set'] = data_set.to_dict('list')
            ad_funcs.background_remove(os.path.join(current_app.config['UPLOAD_FOLDER'], filename))
            result = ad_funcs.compile_report(data_set)
            return render_template("compute.html", response=result, title="Compute")
    return render_template('upload.html', title="Upload")


@bp.route('/download', methods=['GET'])
def download():
    try:
        return send_from_directory(current_app.config['CLIENT_IMAGES'], 'comp_plots.tar', as_attachment=True)
    except FileNotFoundError:
        abort(404)

app/templates/base.html
<html>
    <head>
      {% if title %}
      <title>Welcome to {{ title }} </title>
      {% else %}
      <title>Title is missing!</title>
      {% endif %}
    </head>
    <body>
    <h1>Hello! This is test project based on Flask and statsmodel frameworks!</h1>
    <h2>Please, use "advertising.csv" dataset to perform Linear Model computation, response generation and plots downloading!</h2>
        <hr>
     {% block content %}{% endblock %}
    </body>
</html>

app/templates/compute.html
{% extends "base.html" %}

{% block content %}
<h2>Download link for plots: <a href="{{ url_for('views.download') }}">Download plots!</a></h2>
<h3>JSON response model for Linear Regression!</h3>
<table>
    <tr>
        <td><pre>{{ response|tojson_pretty|safe }}</pre></td>
    </tr>
</table>
{% endblock %}

app/templates/upload.html
{% extends "base.html" %}

{% block content %}
<h2>"Upload advertising.csv" File</h2>
<form method=post enctype=multipart/form-data>
    <input type=file name=file>
    <input type=submit value=Upload>
</form>

{% endblock %}